[package]
name = "kvstore_plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
thenodes = { path = "../../" }
serde_json = "1"
tokio = { version = "1", features = ["rt", "macros"] }
async-trait = "0.1"